# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"choose": "01_simulation.ipynb",
         "simulate_M3RescorlaWagner_v1": "01_simulation.ipynb",
         "plot_rescorla_game": "04_interactive_session.ipynb",
         "simulate_M4ChoiceKernel_v1": "04_interactive_session.ipynb",
         "plot_choice_kernel_game": "04_interactive_session.ipynb"}

modules = ["simulation.py",
           "interactive_session.py"]

doc_url = "https://hgzech.github.io/simulation_workshop/"

git_url = "https://github.com/hgzech/simulation_workshop/tree/master/"

def custom_doc_links(name): return None
